version: '3.7'

services:
  embedbase:
    container_name: embedbase
    image: ghcr.io/another-ai/embedbase:latest
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8000
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./middlewares/history/history.py:/app/middlewares/history.py
      - ./svc.prod.json:/app/svc.prod.json
