version: '3.7'

services:
  embedbase:
    container_name: embedbase
    image: gcr.io/obsidian-ai/embedbase-ava:latest
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8000
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./svc.prod.json:/app/svc.prod.json
