apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: embedbase-ava
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: "true"
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "100"
    spec:
      serviceAccountName: obsidian-ai-cloud-run@obsidian-ai.iam.gserviceaccount.com
      containerConcurrency: 80
      containers:
        image: gcr.io/obsidian-ai/embedbase-ava:0.1.4
        startupProbe:
          httpGet:
            path: /health
          initialDelaySeconds: 30
          successThreshold: 1
          periodSeconds: 30
          timeoutSeconds: 30
          failureThreshold: 30
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /secrets_firebase/svc.prod.json
          - name: SENTRY_RELEASE
            value: "0.1.4"
          - name: ENVIRONMENT
            value: "production"
          - name: UPLOAD_BATCH_SIZE
            value: "100"
          - name: MINIMUM_VERSION
            value: "2.19.0"
        ports:
          - containerPort: 8080
            name: http1
        resources:
          limits:
            cpu: "4"
            memory: 4096Mi
        volumeMounts:
          - name: settings
            readOnly: true
            mountPath: /secrets
          - name: firebase_admin_service_account
            mountPath: /secrets_firebase
            readOnly: true
      volumes:
        - name: settings
          secret:
            secretName: EMBEDBASE_AVA
            items:
              - key: "1"
                path: config.yaml
        - name: firebase_admin_service_account
          secret:
            secretName: FIREBASE_ADMIN_SERVICE_ACCOUNT
            items:
              - key: "1"
                path: svc.prod.json
      timeoutSeconds: 240